package com.whr.baseui.bean

enum class ViewStatusEnum {
    SHOWWAITDIALOG,
    HIDEWAITDIALOG,
    SHOWTOAST,
    SHOWSTATUSEMPTYVIEW,
    SHOWSTATUSERRORVIEW,
    SHOWSTATUSLOADINGVIEW,
    HIDESTATUSVIEW
}
